### ISSUE TITLE
Configure Connected App in Anypoint Platform

### ISSUE THREAD

**Issue by focadiz** [RideXpress/mulesoft#4]
Configure a Connected App in Anypoint Platform to download and backup Design Center projects.

Connected App Permissions should include only Design Center for now.

**Comment by focadiz** [comment]
![Screenshot 2024-10-12 at 6 16 51 PM](https://github.com/user-attachments/assets/c162b785-6156-4cab-9658-016816ae02d5)

**Comment by focadiz** [comment]
This is complete too, please validate and close accordingly

**Comment by ndasanbiagio** [comment]
Closing issue, PR is approved and merged
