### ISSUE TITLE
Configure GitHub Secrets with Connected App Credentials

### ISSUE THREAD

**Issue by focadiz** [RideXpress/mulesoft#5]

**Comment by focadiz** [comment]
![Screenshot 2024-10-12 at 6 17 16 PM](https://github.com/user-attachments/assets/94d0a4f5-e07b-4656-b6cd-0b3fea1a8f56)
![Screenshot 2024-10-12 at 6 17 24 PM](https://github.com/user-attachments/assets/3c33bb87-b691-40e2-8e60-6befbb688fe3)

**Comment by focadiz** [comment]
I think this is complete, please validate and close accordingly

**Comment by ndasanbiagio** [comment]
Closing issue, PR is approved and merged
